web_app/pricehack/config/routes.rb
Rails.application.routes.draw do
  get 'products/index', as: :products
  get 'products/:id/plot' => 'products#plot', as: :product_plot

  get 'dashboard/home', as: :home

  post 'search/find_amazon_prices/' => 'search#find_amazon_prices'
  post 'search/find_amazon_info/' => 'search#find_amazon_info'
  get 'search/find_ebay/:keyword' => 'search#find_ebay'
  get 'search/home' => 'search#home'
  root 'search#home'

  post 'dashboard/search' => 'dashboard#home'
  post 'dashboard/check' => 'dashboard#check'
  delete 'products/index/:id' => "products#destroy", as: :delete_product
end

web_app/pricehack/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ebay_offers
  has_many :prices

  def get_amazon_price(id, product)
    request = Vacuum.new
    request.configure(
      aws_access_key_id: AccessKey.where(provider: :amazon).first.key,
      aws_secret_access_key: AccessKey.where(provider: :amazon).first.secret,
      associate_tag: 'tag'
    )
    response = request.item_lookup(
      query: {
        'ItemId' => id
      }
    )
    url = response.to_h['ItemLookupResponse']["Items"]["Item"]['DetailPageURL']
    agent = Mechanize.new()
    page = agent.get(url)
    a = page.search('#priceblock_ourprice').text.strip.downcase
    a = a[1..-1].to_f
    price = Price.create(count: a, date: Date.today)
    product.prices << price
    product.save
  end

  def fill_amazon_prices
    Product.all.each do |product|
      get_amazon_price(product.amazon_id, product)
    end
  end


  def get_ebay_price(product)
    agent = Mechanize.new()
    offers = product.ebay_offers
    offers.each do |offer|
      page = agent.get(offer.url)
      a = page.search('#prcIsum').text.strip.downcase
      a = a[4..-1].to_f
      price = Price.create(count: a, date: Date.today)
      offer.prices << price
      offer.save
    end
  end

  def fill_ebay_prices
    Product.all.each do |product|
      get_ebay_price(product)
    end
  end 
end

web_app/pricehack/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @price = EbayOffer.last.prices
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_index_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def plot
    @amazon_prices = Product.find(params[:id]).prices
    @ebays_id = Product.find(params[:id]).ebay_offers.collect(&:id)
    @dates = []
    for date in Price.all.collect(&:date).uniq
      @dates << date
    end
    @ebay_prices = Price.where(date: @dates ,ebay_offer_id: @ebays_id)
  end

  private

  def product_params
    params.require(:product).permit(:url)
  end
end

web_app/pricehack/app/helpers/products_helper.rb
module ProductsHelper
end

web_app/pricehack/app/views/products/index.html.slim
table.table
  thead
    tr
      th Amazon id
      th Ebay url
      th Delete
      th Price plot
  tbody
    - @products.each do |product|
      tr
        td=product.amazon_id
        td=product.ebay_offers.collect(&:url)
        td= link_to "Delete Product", delete_product_path(product.id), method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger"
        td= link_to "Product plot", product_plot_path(product.id), class: "btn btn-success"

web_app/pricehack/app/views/products/plot.html.slim
.container
  br/
  h1 Amazon
  = area_chart @amazon_prices.group_by_day(:date).minimum(:count), xtitle: "Date", ytitle: "Price"
  h1 Ebay
  = area_chart @ebay_prices.group_by_day(:date).minimum(:count), xtitle: "Date", ytitle: "Price"